import { clone, create } from "@bufbuild/protobuf";
import * as api from "./import_authority_pb.js";
import type { AuthorizationSignature } from "./owner_records_pb.js";
import type { ProtocolCompatibility } from "../common/contract_pb.js";
import { SignedHostedWitnessStatementV1Schema, HostedWitnessHistoryProofV1Schema, type SignedHostedWitnessStatementV1, type HostedWitnessHistoryProofV1 } from "../common/hosted_witness_pb.js";
import { resolveWitnessStatement, type VerifiedWitnessSet } from "./witness-trust.js";
import { canonicalHybridV1, signingDigest, equal, width, keyId, verifySignature, reject, canonicalHttps, hash } from "./_hybrid-codec.js";
export { canonicalHybridV1, signingDigest, strictDecode, HybridContractError } from "./_hybrid-codec.js";

export const PERMISSION_DOMAIN="heddle-import-member-permission-v1",GENESIS_DOMAIN="heddle-import-genesis-authority-v1",DELEGATION_DOMAIN="heddle-import-job-delegation-v1",RENEWAL_DOMAIN="heddle-import-job-renewal-v1",OPERATION_DOMAIN="heddle-delegated-import-operation-v1",MANIFEST_DOMAIN="heddle-import-result-manifest-v1";
export const MAX_BRANCHES=256,MAX_RECORD_BYTES=65536,MAX_BUNDLE_BYTES=1048576,MAX_RESULT_BYTES=1n<<30n;
export const CANCELLATION_NAMESPACE="heddle-import-cancel-v1";
export const signedPermissionDigest=(v:api.SignedImportMemberPermissionV1)=>signingDigest("heddle-signed-import-member-permission-v1",api.SignedImportMemberPermissionV1Schema,v);
export const signedGenesisDigest=(v:api.SignedImportGenesisAuthorityV1)=>signingDigest("heddle-signed-import-genesis-authority-v1",api.SignedImportGenesisAuthorityV1Schema,v);
export const signedDelegationDigest=(v:api.SignedImportJobDelegationV1)=>signingDigest("heddle-signed-import-job-delegation-v1",api.SignedImportJobDelegationV1Schema,v);
export const signedOperationDigest=(v:api.SignedDelegatedImportOperationV1)=>signingDigest("heddle-signed-delegated-import-operation-v1",api.SignedDelegatedImportOperationV1Schema,v);
export const manifestDigest=(v:api.ImportResultManifestV1)=>signingDigest(MANIFEST_DOMAIN,api.ImportResultManifestV1Schema,v);
export function ownerChainDigest(v:api.ImportOwnerChainV1):Uint8Array{width(v.spoolGenesisDigest,32);if(!v.ownerStateHashes.length||v.ownerStateHashes.length>64||v.transferAuditHashes.length>64)reject("Bounds");for(const h of [...v.ownerStateHashes,...v.transferAuditHashes])width(h,32);for(let i=1;i<v.ownerStateHashes.length;i++){const a=v.ownerStateHashes[i-1]!,b=v.ownerStateHashes[i]!;let cmp=0;for(let j=0;j<32;j++){if(a[j]!==b[j]){cmp=a[j]!-b[j]!;break;}}if(cmp>=0)reject("Canonical");}return signingDigest("heddle-import-owner-chain-v1",api.ImportOwnerChainV1Schema,v);}

function identity(v:api.ImportIdentityV1|undefined):asserts v is api.ImportIdentityV1{if(!v)reject("Canonical");for(const b of [v.spoolUuid,v.ownerAccountUuid]){width(b,16);if(!b.some(Boolean))reject("Canonical");}for(const b of [v.spoolGenesisDigest,v.ownerId,v.ownerStateHash])width(b,32);}
function sameIdentity(a:api.ImportIdentityV1,b:api.ImportIdentityV1):boolean{return equal(canonicalHybridV1(api.ImportIdentityV1Schema,a),canonicalHybridV1(api.ImportIdentityV1Schema,b));}
function interval(start:bigint,end:bigint,now:bigint){if(start<0n||end<=start)reject("Semantic");if(now<start||now>=end)reject("Expired");}
function branch(v:api.ImportBranchLimitV1){if(!v.refName.startsWith("refs/heads/")||v.refName.length>1024||v.refName.endsWith("/")||v.refName.endsWith(".")||v.refName.includes("..")||v.refName.includes("//")||v.refName.includes("@{")||v.refName.split("/").some(p=>p.startsWith(".")||p.endsWith(".lock"))||!/^[A-Za-z0-9/_\-.]+$/.test(v.refName))reject("Canonical");const size=v.hashAlgorithm===1?20:v.hashAlgorithm===2?32:reject("Version");if(v.refMode===1)width(v.pinnedCommitOid,size);else if(v.refMode!==2||v.pinnedCommitOid.length)reject("Semantic");for(const b of [v.genesisDigest,v.targetThreadId,v.expectedFrontierDigest])width(b,32);if(v.maxResultBytes<=0n||v.maxResultBytes>MAX_RESULT_BYTES)reject("Bounds");}
export function validateImportScope(v:api.ImportPermissionScopeV1){canonicalHttps(v.sourceUrl);if(!/^[a-z0-9-]{1,64}$/.test(v.provider)||!v.converterVersion||v.converterVersion.length>128||!/^[\x00-\x7f]+$/.test(v.converterVersion))reject("Canonical");width(v.destinationVersion,32);width(v.optionsDigest,32);if(!v.branches.length||v.branches.length>MAX_BRANCHES||v.maxOperations<=0||v.maxOperations>MAX_BRANCHES||v.maxResultBytes<=0n||v.maxResultBytes>MAX_RESULT_BYTES)reject("Bounds");if(v.maxOperations<v.branches.length)reject("Scope");let total=0n;v.branches.forEach((b,i)=>{branch(b);if(i&&v.branches[i-1]!.refName>=b.refName)reject("Canonical");total+=b.maxResultBytes;});if(total>v.maxResultBytes)reject("Scope");}
function branchSubset(c:api.ImportBranchLimitV1,p:api.ImportBranchLimitV1):boolean{const copy=clone(api.ImportBranchLimitV1Schema,c);copy.maxResultBytes=p.maxResultBytes;return c.maxResultBytes<=p.maxResultBytes&&equal(canonicalHybridV1(api.ImportBranchLimitV1Schema,copy),canonicalHybridV1(api.ImportBranchLimitV1Schema,p));}
function subset(c:api.ImportPermissionScopeV1,p:api.ImportPermissionScopeV1):boolean{return c.provider===p.provider&&c.sourceUrl===p.sourceUrl&&equal(c.destinationVersion,p.destinationVersion)&&equal(c.optionsDigest,p.optionsDigest)&&c.converterVersion===p.converterVersion&&c.maxOperations<=p.maxOperations&&c.maxResultBytes<=p.maxResultBytes&&c.branches.every(b=>p.branches.some(a=>branchSubset(b,a)));}
export interface ImportOwnerExpectation{identity:api.ImportIdentityV1;ownerPublicKey:Uint8Array;ownerChainDigest:Uint8Array;authorityExpiresAtSeconds:bigint;nowUnixSeconds:bigint;forbiddenJobKeys:readonly Uint8Array[];knownJobAssociations:readonly {key:Uint8Array;logicalJobId:Uint8Array}[];}
function snapshotExpectation(e:ImportOwnerExpectation):ImportOwnerExpectation{return {...e,identity:clone(api.ImportIdentityV1Schema,e.identity),ownerPublicKey:e.ownerPublicKey.slice(),ownerChainDigest:e.ownerChainDigest.slice(),forbiddenJobKeys:e.forbiddenJobKeys.map(k=>k.slice()),knownJobAssociations:e.knownJobAssociations.map(a=>({key:a.key.slice(),logicalJobId:a.logicalJobId.slice()}))};}
async function auth(key:Uint8Array,domain:string,schema:Parameters<typeof canonicalHybridV1>[0],body:Parameters<typeof canonicalHybridV1>[1],sig:AuthorizationSignature|undefined){if(!sig||!equal(sig.signerKeyId,keyId(key)))reject("Signature");if(canonicalHybridV1(schema,body).length>MAX_RECORD_BYTES)reject("Bounds");await verifySignature(key,signingDigest(domain,schema,body),sig.signature);}
export async function verifyImportMemberPermission(signed:api.SignedImportMemberPermissionV1,e:ImportOwnerExpectation){e=snapshotExpectation(e);signed=clone(api.SignedImportMemberPermissionV1Schema,signed);const p=signed.body;if(!p||p.formatVersion!==1||p.purpose!==1)reject("ImportPermission");identity(p.identity);if(!sameIdentity(p.identity,e.identity)||!equal(p.ownerChainDigest,e.ownerChainDigest))reject("Root");width(p.logicalJobId,16);width(p.retryLineageId,16);width(p.subjectPublicKey,32);for(const b of [p.cancellationId,p.nonce,p.ownerChainDigest])width(b,32);if(!p.scope)reject("Canonical");validateImportScope(p.scope);interval(p.notBeforeUnixSeconds,p.expiresAtUnixSeconds,e.nowUnixSeconds);if(p.expiresAtUnixSeconds>e.authorityExpiresAtSeconds)reject("Scope");await auth(e.ownerPublicKey,PERMISSION_DOMAIN,api.ImportMemberPermissionV1Schema,p,signed.ownerSignature);}
const checked=new WeakMap<object,{body:api.ImportJobDelegationV1;digest:Uint8Array}>();
export interface VerifiedImportDelegation{readonly body:api.ImportJobDelegationV1;readonly digest:Uint8Array;}
function read(d:VerifiedImportDelegation){return checked.get(d)??reject("Canonical");}
export async function verifyImportDelegation(signed:api.SignedImportJobDelegationV1,member:api.SignedImportMemberPermissionV1|undefined,e:ImportOwnerExpectation):Promise<VerifiedImportDelegation>{
  e=snapshotExpectation(e);member=member?clone(api.SignedImportMemberPermissionV1Schema,member):undefined;
  const snapshot=clone(api.SignedImportJobDelegationV1Schema,signed),d=snapshot.body;if(!d)reject("Canonical");if(d.formatVersion!==1||d.purpose!==1)reject("Version");identity(d.identity);if(!sameIdentity(d.identity,e.identity)||!equal(d.ownerChainDigest,e.ownerChainDigest))reject("Root");for(const b of [d.delegationId,d.logicalJobId,d.retryLineageId]){width(b,16);if(!b.some(Boolean))reject("Canonical");}for(const b of [d.jobPublicKey,d.jobKeyId,d.delegatingPublicKey,d.parentPermissionDigest,d.ownerChainDigest,d.cancellationId,d.predecessorDelegationDigest])width(b,32);if(!equal(d.jobKeyId,keyId(d.jobPublicKey)))reject("Canonical");if(equal(d.jobPublicKey,d.delegatingPublicKey)||equal(d.jobPublicKey,e.ownerPublicKey)||e.forbiddenJobKeys.some(k=>equal(k,d.jobPublicKey)))reject("KeyRole");if(e.knownJobAssociations.some(a=>equal(a.key,d.jobPublicKey)&&!equal(a.logicalJobId,d.logicalJobId)))reject("Scope");if(!d.scope)reject("Canonical");validateImportScope(d.scope);if(d.branchManifest.length!==d.scope.branches.length)reject("Scope");d.branchManifest.forEach((m,i)=>{width(m.genesisAuthorityDigest,32);if(!m.limit||!equal(canonicalHybridV1(api.ImportBranchLimitV1Schema,m.limit),canonicalHybridV1(api.ImportBranchLimitV1Schema,d.scope!.branches[i]!)))reject("Scope");});interval(d.notBeforeUnixSeconds,d.expiresAtUnixSeconds,e.nowUnixSeconds);if(d.expiresAtUnixSeconds>e.authorityExpiresAtSeconds)reject("Scope");
  if(equal(d.delegatingPublicKey,e.ownerPublicKey)){if(member||d.parentPermissionDigest.some(Boolean))reject("ImportPermission");}
  else{if(!member)reject("ImportPermission");await verifyImportMemberPermission(member,e);const p=member.body!;if(!equal(d.parentPermissionDigest,signedPermissionDigest(member))||!equal(d.delegatingPublicKey,p.subjectPublicKey)||!equal(d.logicalJobId,p.logicalJobId)||!equal(d.retryLineageId,p.retryLineageId)||d.notBeforeUnixSeconds<p.notBeforeUnixSeconds||d.expiresAtUnixSeconds>p.expiresAtUnixSeconds||!subset(d.scope,p.scope!))reject("Scope");}
  await auth(d.delegatingPublicKey,DELEGATION_DOMAIN,api.ImportJobDelegationV1Schema,d,snapshot.delegatingSignature);const digest=signedDelegationDigest(snapshot);const result={get body(){return clone(api.ImportJobDelegationV1Schema,d);},get digest(){return digest.slice();}};checked.set(result,{body:d,digest});return result;
}
export async function verifyImportGenesisAuthority(signed:api.SignedImportGenesisAuthorityV1,delegation:VerifiedImportDelegation,genesisDigest:Uint8Array,originalSignature:Uint8Array,envelopeDigest:Uint8Array){const g=signed.body,d=read(delegation).body;if(!g)reject("Canonical");if(g.formatVersion!==1)reject("Version");width(g.originalCreatorSignature,64);for(const b of [g.genesisDigest,g.creatorPublicKey,g.creatorAuthorityEnvelopeDigest,g.parentPermissionDigest,g.ownerChainDigest])width(b,32);if(!g.identity||!sameIdentity(g.identity,d.identity!)||!equal(g.creatorPublicKey,d.delegatingPublicKey)||!equal(g.parentPermissionDigest,d.parentPermissionDigest)||!equal(g.ownerChainDigest,d.ownerChainDigest)||!equal(g.genesisDigest,genesisDigest)||!equal(g.originalCreatorSignature,originalSignature)||!equal(g.creatorAuthorityEnvelopeDigest,envelopeDigest)||!d.branchManifest.some(m=>m.limit&&equal(m.limit.genesisDigest,g.genesisDigest)&&equal(m.genesisAuthorityDigest,signedGenesisDigest(signed))))reject("Scope");await auth(g.creatorPublicKey,GENESIS_DOMAIN,api.ImportGenesisAuthorityV1Schema,g,signed.creatorSignature);}
export async function verifyDelegatedImportOperation(signed:api.SignedDelegatedImportOperationV1,delegation:VerifiedImportDelegation){const o=signed.body,{body:d,digest}=read(delegation);if(!o)reject("Canonical");if(o.formatVersion!==1)reject("Version");width(o.physicalOperationId,16);for(const b of [o.spoolGenesisDigest,o.delegationDigest,o.genesisDigest,o.targetThreadId,o.expectedFrontierDigest,o.resultingFrontierDigest,o.resultingContentDigest,o.optionsDigest])width(b,32);width(o.spoolUuid,16);width(o.logicalJobId,16);width(o.retryLineageId,16);const s=d.scope!,b=s.branches.find(b=>b.refName===o.refName&&b.slotId===o.slotId);if(!b)reject("Scope");width(o.observedCommitOid,o.hashAlgorithm===1?20:o.hashAlgorithm===2?32:reject("Version"));if(!equal(o.spoolUuid,d.identity!.spoolUuid)||!equal(o.spoolGenesisDigest,d.identity!.spoolGenesisDigest)||!equal(o.logicalJobId,d.logicalJobId)||!equal(o.retryLineageId,d.retryLineageId)||!equal(o.delegationDigest,digest)||o.hashAlgorithm!==b.hashAlgorithm||(b.refMode===1&&!equal(o.observedCommitOid,b.pinnedCommitOid))||!equal(o.genesisDigest,b.genesisDigest)||!equal(o.targetThreadId,b.targetThreadId)||!equal(o.expectedFrontierDigest,b.expectedFrontierDigest)||o.resultBytes>b.maxResultBytes||o.resultBytes===0n||!equal(o.optionsDigest,s.optionsDigest)||o.converterVersion!==s.converterVersion)reject("Scope");await auth(d.jobPublicKey,OPERATION_DOMAIN,api.DelegatedImportOperationV1Schema,o,signed.jobSignature);}
export async function verifyNewImportOperation(signed:api.SignedDelegatedImportOperationV1,d:VerifiedImportDelegation,now:bigint){const b=read(d).body;interval(b.notBeforeUnixSeconds,b.expiresAtUnixSeconds,now);await verifyDelegatedImportOperation(signed,d);}
export function validateImportManifest(m:api.ImportResultManifestV1){if(m.formatVersion!==1)reject("Version");width(m.logicalJobId,16);width(m.retryLineageId,16);if(m.slots.length>MAX_BRANCHES)reject("Bounds");m.slots.forEach((s,i)=>{width(s.signedOperationDigest,32);width(s.resultingFrontierDigest,32);if(!s.refName.startsWith("refs/heads/")||!/^[\x00-\x7f]+$/.test(s.refName))reject("Canonical");if(new TextEncoder().encode(s.refName).length>1024||s.resultBytes===0n||s.resultBytes>MAX_RESULT_BYTES)reject("Bounds");const p=m.slots[i-1];if(p&&(p.refName>s.refName||(p.refName===s.refName&&p.slotId>=s.slotId)))reject("Canonical");});}
export async function verifyImportRenewal(signed:api.SignedImportJobRenewalV1,previous:VerifiedImportDelegation,committed:api.ImportResultManifestV1,epoch:bigint,member:api.SignedImportMemberPermissionV1|undefined,e:ImportOwnerExpectation):Promise<VerifiedImportDelegation>{e=snapshotExpectation(e);signed=clone(api.SignedImportJobRenewalV1Schema,signed);committed=clone(api.ImportResultManifestV1Schema,committed);member=member?clone(api.SignedImportMemberPermissionV1Schema,member):undefined;const r=signed.body;if(!r)reject("Canonical");if(r.formatVersion!==1)reject("Version");validateImportManifest(committed);if(r.expectedAuthorityEpoch!==epoch)reject("StaleContext");const old=read(previous);if(!equal(r.predecessorDelegationDigest,old.digest))reject("RenewalFork");if(!equal(r.committedManifestDigest,manifestDigest(committed)))reject("StaleManifest");if(!r.replacement)reject("Canonical");const next=await verifyImportDelegation(r.replacement,member,e),after=read(next).body,before=old.body;if(!equal(after.logicalJobId,before.logicalJobId)||!equal(after.retryLineageId,before.retryLineageId)||!equal(committed.logicalJobId,before.logicalJobId)||!equal(committed.retryLineageId,before.retryLineageId)||!equal(after.identity!.spoolUuid,before.identity!.spoolUuid)||!equal(after.identity!.spoolGenesisDigest,before.identity!.spoolGenesisDigest)||!equal(after.predecessorDelegationDigest,old.digest)||equal(after.jobPublicKey,before.jobPublicKey)||equal(after.delegationId,before.delegationId))reject("RenewalFork");const os=before.scope!,ns=after.scope!;if(!subset(ns,os))reject("RenewalFork");let consumed=0n;for(const slot of committed.slots){const b=os.branches.find(b=>b.refName===slot.refName&&b.slotId===slot.slotId);if(b){if(slot.resultBytes>b.maxResultBytes)reject("RenewalFork");consumed+=slot.resultBytes;}if(ns.branches.some(b=>b.refName===slot.refName&&b.slotId===slot.slotId))reject("CommittedSlot");}const removed=os.branches.filter(b=>committed.slots.some(s=>s.refName===b.refName&&s.slotId===b.slotId)).length;if(ns.maxOperations>os.maxOperations-removed||ns.maxResultBytes>os.maxResultBytes-consumed||after.branchManifest.some(m=>!before.branchManifest.some(old=>equal(old.genesisAuthorityDigest,m.genesisAuthorityDigest)&&old.limit&&m.limit&&old.limit.refName===m.limit.refName&&equal(old.limit.genesisDigest,m.limit.genesisDigest))))reject("RenewalFork");await auth(after.delegatingPublicKey,RENEWAL_DOMAIN,api.ImportJobRenewalV1Schema,r,signed.delegatingSignature);return next;}
export function checkImportSlotReplay(m:api.ImportResultManifestV1,signed:api.SignedDelegatedImportOperationV1):boolean{validateImportManifest(m);const o=signed.body;if(!o)reject("Canonical");if(!equal(m.logicalJobId,o.logicalJobId)||!equal(m.retryLineageId,o.retryLineageId))reject("Scope");const s=m.slots.find(s=>s.refName===o.refName&&s.slotId===o.slotId);if(!s)return false;if(!equal(s.signedOperationDigest,signedOperationDigest(signed))||!equal(s.resultingFrontierDigest,o.resultingFrontierDigest)||s.resultBytes!==o.resultBytes)reject("SlotConflict");return true;}
export function requireHybridPeer(protocol:ProtocolCompatibility|undefined):void{if(!protocol||protocol.protocolVersion!==2||protocol.mandatoryFeatures.length!==1||protocol.mandatoryFeatures[0]!==1)reject("Protocol");}
export async function verifyImportPublication(operation:api.SignedDelegatedImportOperationV1,delegation:VerifiedImportDelegation,manifest:api.ImportResultManifestV1,statement:SignedHostedWitnessStatementV1,set:VerifiedWitnessSet,proof:HostedWitnessHistoryProofV1|undefined,now:bigint){operation=clone(api.SignedDelegatedImportOperationV1Schema,operation);manifest=clone(api.ImportResultManifestV1Schema,manifest);statement=clone(SignedHostedWitnessStatementV1Schema,statement);proof=proof?clone(HostedWitnessHistoryProofV1Schema,proof):undefined;await verifyDelegatedImportOperation(operation,delegation);if(!checkImportSlotReplay(manifest,operation))reject("Scope");const o=operation.body!,{body:d,digest}=read(delegation),s=statement.body,id=d.identity!;if(!s)reject("Canonical");const payload=create(api.ImportPublicationWitnessV1Schema,{formatVersion:1,signedOperationDigest:signedOperationDigest(operation),delegationDigest:digest,logicalJobId:o.logicalJobId,retryLineageId:o.retryLineageId,physicalOperationId:o.physicalOperationId,refName:o.refName,slotId:o.slotId,hashAlgorithm:o.hashAlgorithm,observedCommitOid:o.observedCommitOid,expectedFrontierDigest:o.expectedFrontierDigest,resultingFrontierDigest:o.resultingFrontierDigest,terminalManifestDigest:manifestDigest(manifest)});if(s.purpose!==3||!equal(s.spoolUuid,id.spoolUuid)||!equal(s.spoolGenesisDigest,id.spoolGenesisDigest)||!equal(s.ownerId,id.ownerId)||!equal(s.ownerStateHash,id.ownerStateHash)||s.ownershipTransferSequence!==id.ownershipTransferSequence||!equal(s.authorityDigest,digest)||!operation.jobSignature||!equal(s.originalSignaturesDigest,hash(operation.jobSignature.signature))||!equal(s.canonicalPayload,canonicalHybridV1(api.ImportPublicationWitnessV1Schema,payload))||s.basis!==1)reject("Scope");interval(d.notBeforeUnixSeconds,d.expiresAtUnixSeconds,s.observedAtUnixMillis/1000n);return resolveWitnessStatement(set,statement,proof,false,now);}

export function checkImportJobFence(logicalJobId:Uint8Array,activeDigest:Uint8Array,expectedEpoch:bigint,active:VerifiedImportDelegation,durableEpoch:bigint):void{const d=read(active);if(!equal(logicalJobId,d.body.logicalJobId))reject("Scope");if(expectedEpoch!==durableEpoch||!equal(activeDigest,d.digest))reject("StaleContext");}

export interface ImportSigner{publicKey:Uint8Array;sign(digest:Uint8Array):Promise<Uint8Array>;}
async function signature(domain:string,schema:Parameters<typeof canonicalHybridV1>[0],body:Parameters<typeof canonicalHybridV1>[1],signer:ImportSigner):Promise<AuthorizationSignature>{const digest=signingDigest(domain,schema,body);const signature=await signer.sign(digest);await verifySignature(signer.publicKey,digest,signature);return {$typeName:"heddle.api.v1alpha2.AuthorizationSignature",signerKeyId:keyId(signer.publicKey),signature};}
export async function signImportMemberPermission(body:api.ImportMemberPermissionV1,signer:ImportSigner){const b=clone(api.ImportMemberPermissionV1Schema,body);return create(api.SignedImportMemberPermissionV1Schema,{body:b,ownerSignature:await signature(PERMISSION_DOMAIN,api.ImportMemberPermissionV1Schema,b,signer)});}
export async function signImportGenesisAuthority(body:api.ImportGenesisAuthorityV1,signer:ImportSigner){const b=clone(api.ImportGenesisAuthorityV1Schema,body);if(!equal(b.creatorPublicKey,signer.publicKey))reject("Signature");return create(api.SignedImportGenesisAuthorityV1Schema,{body:b,creatorSignature:await signature(GENESIS_DOMAIN,api.ImportGenesisAuthorityV1Schema,b,signer)});}
export async function signImportDelegation(body:api.ImportJobDelegationV1,signer:ImportSigner){const b=clone(api.ImportJobDelegationV1Schema,body);if(!equal(b.delegatingPublicKey,signer.publicKey))reject("Signature");return create(api.SignedImportJobDelegationV1Schema,{body:b,delegatingSignature:await signature(DELEGATION_DOMAIN,api.ImportJobDelegationV1Schema,b,signer)});}
export async function signImportRenewal(body:api.ImportJobRenewalV1,signer:ImportSigner){const b=clone(api.ImportJobRenewalV1Schema,body);if(!b.replacement?.body||!equal(b.replacement.body.delegatingPublicKey,signer.publicKey))reject("Signature");return create(api.SignedImportJobRenewalV1Schema,{body:b,delegatingSignature:await signature(RENEWAL_DOMAIN,api.ImportJobRenewalV1Schema,b,signer)});}
export async function signDelegatedImportOperation(body:api.DelegatedImportOperationV1,signer:ImportSigner){const b=clone(api.DelegatedImportOperationV1Schema,body);return create(api.SignedDelegatedImportOperationV1Schema,{body:b,jobSignature:await signature(OPERATION_DOMAIN,api.DelegatedImportOperationV1Schema,b,signer)});}

import { toBinary } from "@bufbuild/protobuf";
import { SignedRecordSchema, type SignedRecord, type RecordSignature } from "./common_pb.js";
import { compare, sized, utf8, u32, join } from "./_hybrid-codec.js";
import { unarySigningBytes } from "../signing.js";
import { threadGenesisId } from "./thread-genesis.js";

export type ImportPermissionEvidence = {kind:"import";record:api.SignedImportMemberPermissionV1} | {kind:"owner_capability";record:import("./owner_records_pb.js").SignedOwnerCapability} | {kind:"online_role";role:string};
export function selectImportPermission(e:ImportPermissionEvidence):api.SignedImportMemberPermissionV1{if(e.kind!=="import")reject("ImportPermission");return e.record;}
export function requireImportOperationFormat(format:string):void{if(format!==OPERATION_DOMAIN)reject("Protocol");}
export function frontierDigest(f:api.ImportFrontierV1):Uint8Array{if(f.formatVersion!==1)reject("Version");width(f.threadId,32);if(f.operationIds.length>128)reject("Bounds");f.operationIds.forEach((id,i)=>{width(id,32);if(i&&compare(f.operationIds[i-1]!,id)>=0)reject("Canonical");});return signingDigest("heddle-import-frontier-v1",api.ImportFrontierV1Schema,f);}
export function contentDigest(c:api.ImportContentV1):Uint8Array{if(c.formatVersion!==1)reject("Version");if(!c.canonicalCapture.length||BigInt(c.canonicalCapture.length)>MAX_RESULT_BYTES)reject("Bounds");return signingDigest("heddle-import-content-v1",api.ImportContentV1Schema,c);}
export const signedNativeDigest=(r:SignedRecord)=>signingDigest("heddle-signed-native-record-v1",SignedRecordSchema,r);
async function native(r:SignedRecord,format:string){if(r.format!==format)reject("Version");if(!r.canonicalRecord.length||r.canonicalRecord.length>65536||!r.signatures.length||r.signatures.length>16)reject("Bounds");for(let i=0;i<r.signatures.length;i++){const s=r.signatures[i]!;if(i&&compare(r.signatures[i-1]!.publicKey,s.publicKey)>=0)reject("Canonical");await verifySignature(s.publicKey,join(utf8.encode(format),Uint8Array.of(0),r.canonicalRecord),s.signature);}}
async function dependencies(records:SignedRecord[]){if(records.length>128)reject("Bounds");for(let i=0;i<records.length;i++){const r=records[i]!;if(!["heddle-thread-genesis-v1","heddle-thread-operation-v1","heddle-thread-ownership-claim-v1","heddle-thread-ownership-resolution-v1"].includes(r.format))reject("Version");await native(r,r.format);if(i&&compare(signedNativeDigest(records[i-1]!),signedNativeDigest(r))>=0)reject("Canonical");}}
export function originalSignaturesDigest(records:SignedRecord[],extra:RecordSignature[]=[]):Uint8Array{const signatures=[...records.flatMap(r=>r.signatures),...extra];return hash(utf8.encode("heddle-hosted-original-signatures-v1"),u32(signatures.length),...signatures.flatMap(s=>[sized(s.publicKey),sized(s.signature)]));}
export const authorityEnvelopeDigest=(e:Uint8Array)=>hash(utf8.encode("heddle-hosted-authority-envelope-v1"),sized(e));
export type WitnessPayload={kind:"genesis";payload:api.ImportGenesisWitnessV1}|{kind:"authority";payload:api.ImportAuthorityWitnessV1}|{kind:"landing";payload:api.HostedLandingWitnessV1};
/** Supply independently verified native objects/authority and accepted context.
 * Exact matching + original signatures are separate from witness resolution. */
export async function verifyWitnessPayload(s:import("../common/hosted_witness_pb.js").HostedWitnessStatementV1,payload:WitnessPayload):Promise<void>{
  s=clone((await import("../common/hosted_witness_pb.js")).HostedWitnessStatementV1Schema,s);
  let purpose:number,bytes:Uint8Array,authority:Uint8Array,signatures:Uint8Array,publisher=s.publisherKeyId;
  if(payload.kind==="genesis"){const p=clone(api.ImportGenesisWitnessV1Schema,payload.payload);if(p.formatVersion!==1)reject("Version");if(!p.binding?.body||!p.originalGenesis)reject("Canonical");const b=p.binding.body;await native(p.originalGenesis,"heddle-thread-genesis-v1");if(!equal(threadGenesisId(p.originalGenesis.canonicalRecord),b.genesisDigest)||!b.identity||!equal(s.spoolUuid,b.identity.spoolUuid)||!equal(s.spoolGenesisDigest,b.identity.spoolGenesisDigest)||!equal(s.ownerId,b.identity.ownerId)||!equal(s.ownerStateHash,b.identity.ownerStateHash)||s.ownershipTransferSequence!==b.identity.ownershipTransferSequence)reject("Scope");const creator=p.originalGenesis.signatures.find(x=>equal(x.publicKey,b.creatorPublicKey));if(!creator)reject("Signature");if(!equal(b.originalCreatorSignature,creator.signature)||!equal(b.creatorAuthorityEnvelopeDigest,hash(p.creatorAuthorityEnvelope)))reject("Scope");await auth(b.creatorPublicKey,GENESIS_DOMAIN,api.ImportGenesisAuthorityV1Schema,b,p.binding.creatorSignature);purpose=1;bytes=canonicalHybridV1(api.ImportGenesisWitnessV1Schema,p);authority=signedGenesisDigest(p.binding);signatures=originalSignaturesDigest([p.originalGenesis]);publisher=keyId(b.creatorPublicKey);}
  else if(payload.kind==="authority"){const p=clone(api.ImportAuthorityWitnessV1Schema,payload.payload);if(p.formatVersion!==1)reject("Version");if(!p.original)reject("Canonical");const format=["","heddle-thread-operation-v1","heddle-thread-ownership-claim-v1","heddle-thread-ownership-resolution-v1"][p.kind];if(!format)reject("Version");await native(p.original,format);if((p.kind===2||p.kind===3)&&p.original.signatures.length!==2)reject("Signature");if(!p.original.signatures.some(x=>equal(keyId(x.publicKey),s.publisherKeyId)))reject("Signature");if(!p.authorityEnvelope.length||p.authorityEnvelope.length>MAX_RECORD_BYTES)reject("Bounds");await dependencies(p.dependencies);purpose=2;bytes=canonicalHybridV1(api.ImportAuthorityWitnessV1Schema,p);authority=authorityEnvelopeDigest(p.authorityEnvelope);signatures=originalSignaturesDigest([p.original,...p.dependencies]);}
  else{const p=clone(api.HostedLandingWitnessV1Schema,payload.payload);if(p.formatVersion!==1)reject("Version");if(!p.execution||!p.sourceOperation||!p.request?.signature)reject("Canonical");const r=p.request;if(r.formatVersion!==1||r.methodPath!=="/heddle.api.v1alpha2.ThreadService/LandThread")reject("Version");await native(p.execution,"heddle-thread-operation-v1");await native(p.sourceOperation,"heddle-thread-operation-v1");await dependencies(p.reviewEvidence);if(r.signingIdentity!==`principal:device-key:${Array.from(r.signature!.publicKey,b=>b.toString(16).padStart(2,"0")).join("")}`)reject("Signature");width(r.nonce,16);if(r.timestampMillis<=0n||!r.requestBody.length||r.requestBody.length>MAX_RECORD_BYTES||!p.authorityEnvelope.length||p.authorityEnvelope.length>MAX_RECORD_BYTES)reject("Bounds");await verifySignature(r.signature!.publicKey,await unarySigningBytes(r.signingIdentity,r.methodPath,r.timestampMillis,r.nonce,r.requestBody),r.signature!.signature);purpose=4;bytes=canonicalHybridV1(api.HostedLandingWitnessV1Schema,p);authority=authorityEnvelopeDigest(p.authorityEnvelope);signatures=originalSignaturesDigest([p.execution,p.sourceOperation,...p.reviewEvidence],[r.signature!]);publisher=keyId(r.signature!.publicKey);}
  if(bytes.length>MAX_RECORD_BYTES)reject("Bounds");if(s.purpose!==purpose||!equal(s.canonicalPayload,bytes)||!equal(s.authorityDigest,authority)||!equal(s.originalSignaturesDigest,signatures)||!equal(s.publisherKeyId,publisher))reject("Scope");
}
export function resolveBundlePermission(bundle:api.ImportPublicProofBundleV1,digest:Uint8Array):api.SignedImportMemberPermissionV1|undefined{width(digest,32);if(!digest.some(Boolean))return;return bundle.memberPermissions.find(p=>equal(signedPermissionDigest(p),digest))??reject("ImportPermission");}
export function resolveBundleManifest(bundle:api.ImportPublicProofBundleV1,digest:Uint8Array):api.ImportResultManifestV1{width(digest,32);return bundle.manifests.find(m=>equal(manifestDigest(m),digest))??reject("StaleManifest");}
export function publicationPayload(operation:api.SignedDelegatedImportOperationV1,m:api.ImportResultManifestV1):api.ImportPublicationWitnessV1{const o=operation.body??reject("Canonical");return create(api.ImportPublicationWitnessV1Schema,{formatVersion:1,signedOperationDigest:signedOperationDigest(operation),delegationDigest:o.delegationDigest,logicalJobId:o.logicalJobId,retryLineageId:o.retryLineageId,physicalOperationId:o.physicalOperationId,refName:o.refName,slotId:o.slotId,hashAlgorithm:o.hashAlgorithm,observedCommitOid:o.observedCommitOid,expectedFrontierDigest:o.expectedFrontierDigest,resultingFrontierDigest:o.resultingFrontierDigest,terminalManifestDigest:manifestDigest(m)});}
export function validatePublicBundle(b:api.ImportPublicProofBundleV1):void{
  if(b.formatVersion!==1)reject("Version");if(toBinary(api.ImportPublicProofBundleV1Schema,b).length>MAX_BUNDLE_BYTES||b.ownerHistories.length>64||b.ownershipTransfers.length>64||b.delegations.length>64||b.renewals.length>63||b.memberPermissions.length>64||b.manifests.length>320||b.operations.length>256||b.genesisAuthorities.length>256||b.originalGeneses.length>256||b.creatorAuthorityEnvelopes.length>256||b.statements.length>1024||b.historyProofs.length>1024||b.policies.length>256||b.genesisWitnesses.length>256||b.authorityWitnesses.length>256||b.landingWitnesses.length>256)reject("Bounds");
  for(const {body:s} of b.statements){if(!s)reject("Canonical");requirePolicyHistory(b,s.spoolUuid,s.policySequence,s.policyStateHash);}
  for(const list of [b.memberPermissions.map(signedPermissionDigest),b.manifests.map(manifestDigest)])for(let i=1;i<list.length;i++)if(compare(list[i-1]!,list[i]!)>=0)reject("Canonical");
  if(b.memberPermission&&!equal(canonicalHybridV1(api.SignedImportMemberPermissionV1Schema,resolveBundlePermission(b,signedPermissionDigest(b.memberPermission))!),canonicalHybridV1(api.SignedImportMemberPermissionV1Schema,b.memberPermission)))reject("ImportPermission");const terminal=b.terminalManifest??reject("Canonical");resolveBundleManifest(b,manifestDigest(terminal));if(!b.delegations.length||b.renewals.length+1!==b.delegations.length)reject("Canonical");
  b.delegations.forEach((d,i)=>{const body=d.body??reject("Canonical");resolveBundlePermission(b,body.parentPermissionDigest);if(!i){if(body.predecessorDelegationDigest.some(Boolean))reject("RenewalFork");}else{const r=b.renewals[i-1]!.body??reject("Canonical");if(!r.replacement||!equal(signedDelegationDigest(r.replacement),signedDelegationDigest(d))||!equal(r.predecessorDelegationDigest,signedDelegationDigest(b.delegations[i-1]!))||!equal(body.predecessorDelegationDigest,r.predecessorDelegationDigest)||r.expectedAuthorityEpoch!==BigInt(i))reject("RenewalFork");resolveBundleManifest(b,r.committedManifestDigest);}for(const branch of body.branchManifest){const g=b.genesisAuthorities.find(g=>equal(signedGenesisDigest(g),branch.genesisAuthorityDigest))?.body??reject("Scope");resolveBundlePermission(b,g.parentPermissionDigest);if(!b.originalGeneses.some(o=>equal(threadGenesisId(o.canonicalRecord),g.genesisDigest))||!b.creatorAuthorityEnvelopes.some(e=>equal(hash(e),g.creatorAuthorityEnvelopeDigest)))reject("Scope");if(!b.genesisWitnesses.some(p=>p.binding&&equal(signedGenesisDigest(p.binding),branch.genesisAuthorityDigest)&&p.originalGenesis&&equal(threadGenesisId(p.originalGenesis.canonicalRecord),g.genesisDigest)&&b.originalGeneses.some(o=>equal(signedNativeDigest(o),signedNativeDigest(p.originalGenesis!)))&&equal(hash(p.creatorAuthorityEnvelope),g.creatorAuthorityEnvelopeDigest)&&b.statements.some(s=>s.body?.purpose===1&&equal(s.body.canonicalPayload,canonicalHybridV1(api.ImportGenesisWitnessV1Schema,p)))))reject("Scope");}});
  for(const m of b.manifests){validateImportManifest(m);if(!equal(m.logicalJobId,terminal.logicalJobId)||!equal(m.retryLineageId,terminal.retryLineageId))reject("Scope");for(const slot of m.slots){const o=b.operations.find(o=>equal(signedOperationDigest(o),slot.signedOperationDigest))??reject("Scope");if(!checkImportSlotReplay(m,o)||!checkImportSlotReplay(terminal,o))reject("Scope");}}
  for(const o of b.operations){if(!o.body||!b.delegations.some(d=>equal(signedDelegationDigest(d),o.body!.delegationDigest))||!checkImportSlotReplay(terminal,o)||!b.manifests.some(m=>checkImportSlotReplay(m,o)&&b.statements.some(s=>s.body?.purpose===3&&equal(s.body.canonicalPayload,canonicalHybridV1(api.ImportPublicationWitnessV1Schema,publicationPayload(o,m))))))reject("Scope");}
  for(const {body:s} of b.statements){if(!s)reject("Canonical");const payloads=s.purpose===1?b.genesisWitnesses.map(p=>canonicalHybridV1(api.ImportGenesisWitnessV1Schema,p)):s.purpose===2?b.authorityWitnesses.map(p=>canonicalHybridV1(api.ImportAuthorityWitnessV1Schema,p)):s.purpose===4?b.landingWitnesses.map(p=>canonicalHybridV1(api.HostedLandingWitnessV1Schema,p)):s.purpose===3?b.operations.flatMap(o=>b.manifests.map(m=>canonicalHybridV1(api.ImportPublicationWitnessV1Schema,publicationPayload(o,m)))):reject("Version");if(!payloads.some(p=>equal(p,s.canonicalPayload)))reject("Scope");}
}
// Reference completeness; native verification authenticates policy and owner context.
function requirePolicyHistory(b:api.ImportPublicProofBundleV1,spool:Uint8Array,sequence:bigint,stateHash:Uint8Array):void{
  for(let i=0;i<=b.policies.length;i++){
    width(stateHash,32);if(sequence===0n){if(stateHash.some(Boolean))reject("Scope");return;}
    const matches=b.policies.filter(p=>p.body&&equal(p.body.spoolUuid,spool)&&p.body.sequence===sequence&&equal(p.body.policyStateHash,stateHash));
    if(!matches.length)reject("Scope");if(matches.length!==1)reject("Canonical");const head=matches[0]!.body!.expectedHead??reject("Canonical");if(head.sequence+1n!==sequence)reject("Scope");sequence=head.sequence;stateHash=head.stateHash;
  }
  reject("Scope");
}
export function validateRenewalPreparation(response:api.PrepareImportJobResponse):void{const s=response.renewalState,p=response.proposal;if(!s?.activePredecessor?.body||!s.committedManifest||!p)reject("Canonical");const old=s.activePredecessor.body,m=s.committedManifest;validateImportManifest(m);if(s.formatVersion!==1||s.authorityEpoch===0n||!equal(s.logicalJobId,old.logicalJobId)||!equal(s.retryLineageId,old.retryLineageId)||!equal(p.logicalJobId,s.logicalJobId)||!equal(p.retryLineageId,s.retryLineageId)||!equal(m.logicalJobId,s.logicalJobId)||!equal(m.retryLineageId,s.retryLineageId)||!equal(p.predecessorDelegationDigest,signedDelegationDigest(s.activePredecessor)))reject("StaleContext");}
