import { clone, create } from "@bufbuild/protobuf";
import * as api from "./import_authority_pb.js";
import type { AuthorizationSignature } from "./owner_records_pb.js";
import type { ProtocolCompatibility } from "../common/contract_pb.js";
import type { SignedHostedWitnessStatementV1, HostedWitnessHistoryProofV1 } from "../common/hosted_witness_pb.js";
import { resolveWitnessStatement, type VerifiedWitnessSet } from "./witness-trust.js";
import { canonicalHybridV1, signingDigest, equal, width, keyId, verifySignature, reject, canonicalHttps, hash } from "./_hybrid-codec.js";
export { canonicalHybridV1, signingDigest, strictDecode, HybridContractError } from "./_hybrid-codec.js";

export const PERMISSION_DOMAIN="heddle-import-member-permission-v1",GENESIS_DOMAIN="heddle-import-genesis-authority-v1",DELEGATION_DOMAIN="heddle-import-job-delegation-v1",RENEWAL_DOMAIN="heddle-import-job-renewal-v1",OPERATION_DOMAIN="heddle-delegated-import-operation-v1",MANIFEST_DOMAIN="heddle-import-result-manifest-v1";
export const MAX_BRANCHES=256,MAX_RECORD_BYTES=65536,MAX_BUNDLE_BYTES=1048576,MAX_RESULT_BYTES=1n<<30n;
export const CANCELLATION_NAMESPACE="heddle-import-cancel-v1";
export const signedPermissionDigest=(v:api.SignedImportMemberPermissionV1)=>signingDigest("heddle-signed-import-member-permission-v1",api.SignedImportMemberPermissionV1Schema,v);
export const signedGenesisDigest=(v:api.SignedImportGenesisAuthorityV1)=>signingDigest("heddle-signed-import-genesis-authority-v1",api.SignedImportGenesisAuthorityV1Schema,v);
export const signedDelegationDigest=(v:api.SignedImportJobDelegationV1)=>signingDigest("heddle-signed-import-job-delegation-v1",api.SignedImportJobDelegationV1Schema,v);
export const signedOperationDigest=(v:api.SignedDelegatedImportOperationV1)=>signingDigest("heddle-signed-delegated-import-operation-v1",api.SignedDelegatedImportOperationV1Schema,v);
export const manifestDigest=(v:api.ImportResultManifestV1)=>signingDigest(MANIFEST_DOMAIN,api.ImportResultManifestV1Schema,v);
export function ownerChainDigest(v:api.ImportOwnerChainV1):Uint8Array{width(v.spoolGenesisDigest,32);if(!v.ownerStateHashes.length||v.ownerStateHashes.length>64||v.transferAuditHashes.length>64)reject("Bounds");for(const h of [...v.ownerStateHashes,...v.transferAuditHashes])width(h,32);for(let i=1;i<v.ownerStateHashes.length;i++){const a=v.ownerStateHashes[i-1]!,b=v.ownerStateHashes[i]!;let cmp=0;for(let j=0;j<32;j++){if(a[j]!==b[j]){cmp=a[j]!-b[j]!;break;}}if(cmp>=0)reject("Canonical");}return signingDigest("heddle-import-owner-chain-v1",api.ImportOwnerChainV1Schema,v);}

function identity(v:api.ImportIdentityV1|undefined):asserts v is api.ImportIdentityV1{if(!v)reject("Canonical");for(const b of [v.spoolUuid,v.ownerAccountUuid]){width(b,16);if(!b.some(Boolean))reject("Canonical");}for(const b of [v.spoolGenesisDigest,v.ownerId,v.ownerStateHash])width(b,32);}
function sameIdentity(a:api.ImportIdentityV1,b:api.ImportIdentityV1):boolean{return equal(canonicalHybridV1(api.ImportIdentityV1Schema,a),canonicalHybridV1(api.ImportIdentityV1Schema,b));}
function interval(start:bigint,end:bigint,now:bigint){if(start<0n||end<=start)reject("Semantic");if(now<start||now>=end)reject("Expired");}
function branch(v:api.ImportBranchLimitV1){if(!v.refName.startsWith("refs/heads/")||v.refName.length>1024||v.refName.endsWith("/")||v.refName.endsWith(".")||v.refName.includes("..")||v.refName.includes("//")||v.refName.includes("@{")||v.refName.split("/").some(p=>p.startsWith(".")||p.endsWith(".lock"))||!/^[A-Za-z0-9/_\-.]+$/.test(v.refName))reject("Canonical");const size=v.hashAlgorithm===1?20:v.hashAlgorithm===2?32:reject("Version");if(v.refMode===1)width(v.pinnedCommitOid,size);else if(v.refMode!==2||v.pinnedCommitOid.length)reject("Semantic");for(const b of [v.genesisDigest,v.targetThreadId,v.expectedFrontierDigest])width(b,32);if(v.maxResultBytes<=0n||v.maxResultBytes>MAX_RESULT_BYTES)reject("Bounds");}
export function validateImportScope(v:api.ImportPermissionScopeV1){canonicalHttps(v.sourceUrl);if(!/^[a-z0-9-]{1,64}$/.test(v.provider)||!v.converterVersion||v.converterVersion.length>128||!/^[\x00-\x7f]+$/.test(v.converterVersion))reject("Canonical");width(v.destinationVersion,32);width(v.optionsDigest,32);if(!v.branches.length||v.branches.length>MAX_BRANCHES||v.maxOperations<=0||v.maxOperations>MAX_BRANCHES||v.maxResultBytes<=0n||v.maxResultBytes>MAX_RESULT_BYTES)reject("Bounds");if(v.maxOperations<v.branches.length)reject("Scope");let total=0n;v.branches.forEach((b,i)=>{branch(b);if(i&&v.branches[i-1]!.refName>=b.refName)reject("Canonical");total+=b.maxResultBytes;});if(total>v.maxResultBytes)reject("Scope");}
function branchSubset(c:api.ImportBranchLimitV1,p:api.ImportBranchLimitV1):boolean{const copy=clone(api.ImportBranchLimitV1Schema,c);copy.maxResultBytes=p.maxResultBytes;return c.maxResultBytes<=p.maxResultBytes&&equal(canonicalHybridV1(api.ImportBranchLimitV1Schema,copy),canonicalHybridV1(api.ImportBranchLimitV1Schema,p));}
function subset(c:api.ImportPermissionScopeV1,p:api.ImportPermissionScopeV1):boolean{return c.provider===p.provider&&c.sourceUrl===p.sourceUrl&&equal(c.destinationVersion,p.destinationVersion)&&equal(c.optionsDigest,p.optionsDigest)&&c.converterVersion===p.converterVersion&&c.maxOperations<=p.maxOperations&&c.maxResultBytes<=p.maxResultBytes&&c.branches.every(b=>p.branches.some(a=>branchSubset(b,a)));}
export interface ImportOwnerExpectation{identity:api.ImportIdentityV1;ownerPublicKey:Uint8Array;ownerChainDigest:Uint8Array;authorityExpiresAtSeconds:bigint;nowUnixSeconds:bigint;forbiddenJobKeys:readonly Uint8Array[];knownJobAssociations:readonly {key:Uint8Array;logicalJobId:Uint8Array}[];}
async function auth(key:Uint8Array,domain:string,schema:Parameters<typeof canonicalHybridV1>[0],body:Parameters<typeof canonicalHybridV1>[1],sig:AuthorizationSignature|undefined){if(!sig||!equal(sig.signerKeyId,keyId(key)))reject("Signature");if(canonicalHybridV1(schema,body).length>MAX_RECORD_BYTES)reject("Bounds");await verifySignature(key,signingDigest(domain,schema,body),sig.signature);}
export async function verifyImportMemberPermission(signed:api.SignedImportMemberPermissionV1,e:ImportOwnerExpectation){const p=signed.body;if(!p||p.formatVersion!==1||p.purpose!==1)reject("ImportPermission");identity(p.identity);if(!sameIdentity(p.identity,e.identity)||!equal(p.ownerChainDigest,e.ownerChainDigest))reject("Root");width(p.logicalJobId,16);width(p.retryLineageId,16);width(p.subjectPublicKey,32);for(const b of [p.cancellationId,p.nonce,p.ownerChainDigest])width(b,32);if(!p.scope)reject("Canonical");validateImportScope(p.scope);interval(p.notBeforeUnixSeconds,p.expiresAtUnixSeconds,e.nowUnixSeconds);if(p.expiresAtUnixSeconds>e.authorityExpiresAtSeconds)reject("Scope");await auth(e.ownerPublicKey,PERMISSION_DOMAIN,api.ImportMemberPermissionV1Schema,p,signed.ownerSignature);}
const checked=new WeakMap<object,{body:api.ImportJobDelegationV1;digest:Uint8Array}>();
export interface VerifiedImportDelegation{readonly body:api.ImportJobDelegationV1;readonly digest:Uint8Array;}
function read(d:VerifiedImportDelegation){return checked.get(d)??reject("Canonical");}
export async function verifyImportDelegation(signed:api.SignedImportJobDelegationV1,member:api.SignedImportMemberPermissionV1|undefined,e:ImportOwnerExpectation):Promise<VerifiedImportDelegation>{
  const snapshot=clone(api.SignedImportJobDelegationV1Schema,signed),d=snapshot.body;if(!d)reject("Canonical");if(d.formatVersion!==1||d.purpose!==1)reject("Version");identity(d.identity);if(!sameIdentity(d.identity,e.identity)||!equal(d.ownerChainDigest,e.ownerChainDigest))reject("Root");for(const b of [d.delegationId,d.logicalJobId,d.retryLineageId]){width(b,16);if(!b.some(Boolean))reject("Canonical");}for(const b of [d.jobPublicKey,d.jobKeyId,d.delegatingPublicKey,d.parentPermissionDigest,d.ownerChainDigest,d.cancellationId,d.predecessorDelegationDigest])width(b,32);if(!equal(d.jobKeyId,keyId(d.jobPublicKey)))reject("Canonical");if(equal(d.jobPublicKey,d.delegatingPublicKey)||equal(d.jobPublicKey,e.ownerPublicKey)||e.forbiddenJobKeys.some(k=>equal(k,d.jobPublicKey)))reject("KeyRole");if(e.knownJobAssociations.some(a=>equal(a.key,d.jobPublicKey)&&!equal(a.logicalJobId,d.logicalJobId)))reject("Scope");if(!d.scope)reject("Canonical");validateImportScope(d.scope);if(d.branchManifest.length!==d.scope.branches.length)reject("Scope");d.branchManifest.forEach((m,i)=>{width(m.genesisAuthorityDigest,32);if(!m.limit||!equal(canonicalHybridV1(api.ImportBranchLimitV1Schema,m.limit),canonicalHybridV1(api.ImportBranchLimitV1Schema,d.scope!.branches[i]!)))reject("Scope");});interval(d.notBeforeUnixSeconds,d.expiresAtUnixSeconds,e.nowUnixSeconds);if(d.expiresAtUnixSeconds>e.authorityExpiresAtSeconds)reject("Scope");
  if(equal(d.delegatingPublicKey,e.ownerPublicKey)){if(member||d.parentPermissionDigest.some(Boolean))reject("ImportPermission");}
  else{if(!member)reject("ImportPermission");await verifyImportMemberPermission(member,e);const p=member.body!;if(!equal(d.parentPermissionDigest,signedPermissionDigest(member))||!equal(d.delegatingPublicKey,p.subjectPublicKey)||!equal(d.logicalJobId,p.logicalJobId)||!equal(d.retryLineageId,p.retryLineageId)||d.notBeforeUnixSeconds<p.notBeforeUnixSeconds||d.expiresAtUnixSeconds>p.expiresAtUnixSeconds||!subset(d.scope,p.scope!))reject("Scope");}
  await auth(d.delegatingPublicKey,DELEGATION_DOMAIN,api.ImportJobDelegationV1Schema,d,snapshot.delegatingSignature);const digest=signedDelegationDigest(snapshot);const result={get body(){return clone(api.ImportJobDelegationV1Schema,d);},get digest(){return digest.slice();}};checked.set(result,{body:d,digest});return result;
}
export async function verifyImportGenesisAuthority(signed:api.SignedImportGenesisAuthorityV1,delegation:VerifiedImportDelegation,genesisDigest:Uint8Array,originalSignature:Uint8Array,envelopeDigest:Uint8Array){const g=signed.body,d=read(delegation).body;if(!g)reject("Canonical");if(g.formatVersion!==1)reject("Version");width(g.originalCreatorSignature,64);for(const b of [g.genesisDigest,g.creatorPublicKey,g.creatorAuthorityEnvelopeDigest,g.parentPermissionDigest,g.ownerChainDigest])width(b,32);if(!g.identity||!sameIdentity(g.identity,d.identity!)||!equal(g.creatorPublicKey,d.delegatingPublicKey)||!equal(g.parentPermissionDigest,d.parentPermissionDigest)||!equal(g.ownerChainDigest,d.ownerChainDigest)||!equal(g.genesisDigest,genesisDigest)||!equal(g.originalCreatorSignature,originalSignature)||!equal(g.creatorAuthorityEnvelopeDigest,envelopeDigest)||!d.branchManifest.some(m=>m.limit&&equal(m.limit.genesisDigest,g.genesisDigest)&&equal(m.genesisAuthorityDigest,signedGenesisDigest(signed))))reject("Scope");await auth(g.creatorPublicKey,GENESIS_DOMAIN,api.ImportGenesisAuthorityV1Schema,g,signed.creatorSignature);}
export async function verifyDelegatedImportOperation(signed:api.SignedDelegatedImportOperationV1,delegation:VerifiedImportDelegation){const o=signed.body,{body:d,digest}=read(delegation);if(!o)reject("Canonical");if(o.formatVersion!==1)reject("Version");width(o.physicalOperationId,16);for(const b of [o.spoolGenesisDigest,o.delegationDigest,o.genesisDigest,o.targetThreadId,o.expectedFrontierDigest,o.resultingFrontierDigest,o.resultingContentDigest,o.optionsDigest])width(b,32);width(o.spoolUuid,16);width(o.logicalJobId,16);width(o.retryLineageId,16);const s=d.scope!,b=s.branches.find(b=>b.refName===o.refName&&b.slotId===o.slotId);if(!b)reject("Scope");width(o.observedCommitOid,o.hashAlgorithm===1?20:o.hashAlgorithm===2?32:reject("Version"));if(!equal(o.spoolUuid,d.identity!.spoolUuid)||!equal(o.spoolGenesisDigest,d.identity!.spoolGenesisDigest)||!equal(o.logicalJobId,d.logicalJobId)||!equal(o.retryLineageId,d.retryLineageId)||!equal(o.delegationDigest,digest)||o.hashAlgorithm!==b.hashAlgorithm||(b.refMode===1&&!equal(o.observedCommitOid,b.pinnedCommitOid))||!equal(o.genesisDigest,b.genesisDigest)||!equal(o.targetThreadId,b.targetThreadId)||!equal(o.expectedFrontierDigest,b.expectedFrontierDigest)||o.resultBytes>b.maxResultBytes||o.resultBytes===0n||!equal(o.optionsDigest,s.optionsDigest)||o.converterVersion!==s.converterVersion)reject("Scope");await auth(d.jobPublicKey,OPERATION_DOMAIN,api.DelegatedImportOperationV1Schema,o,signed.jobSignature);}
export async function verifyNewImportOperation(signed:api.SignedDelegatedImportOperationV1,d:VerifiedImportDelegation,now:bigint){const b=read(d).body;interval(b.notBeforeUnixSeconds,b.expiresAtUnixSeconds,now);await verifyDelegatedImportOperation(signed,d);}
export function validateImportManifest(m:api.ImportResultManifestV1){if(m.formatVersion!==1)reject("Version");width(m.logicalJobId,16);width(m.retryLineageId,16);if(m.slots.length>MAX_BRANCHES)reject("Bounds");m.slots.forEach((s,i)=>{width(s.signedOperationDigest,32);width(s.resultingFrontierDigest,32);if(s.refName.length>1024||s.resultBytes===0n||s.resultBytes>MAX_RESULT_BYTES)reject("Bounds");const p=m.slots[i-1];if(p&&(p.refName>s.refName||(p.refName===s.refName&&p.slotId>=s.slotId)))reject("Canonical");});}
export async function verifyImportRenewal(signed:api.SignedImportJobRenewalV1,previous:VerifiedImportDelegation,committed:api.ImportResultManifestV1,epoch:bigint,member:api.SignedImportMemberPermissionV1|undefined,e:ImportOwnerExpectation):Promise<VerifiedImportDelegation>{const r=signed.body;if(!r)reject("Canonical");if(r.formatVersion!==1)reject("Version");validateImportManifest(committed);if(r.expectedAuthorityEpoch!==epoch)reject("StaleContext");const old=read(previous);if(!equal(r.predecessorDelegationDigest,old.digest)||!equal(r.committedManifestDigest,manifestDigest(committed)))reject("RenewalFork");if(!r.replacement)reject("Canonical");const next=await verifyImportDelegation(r.replacement,member,e),after=read(next).body,before=old.body;if(!equal(after.logicalJobId,before.logicalJobId)||!equal(after.retryLineageId,before.retryLineageId)||!equal(committed.logicalJobId,before.logicalJobId)||!equal(committed.retryLineageId,before.retryLineageId)||!equal(after.identity!.spoolUuid,before.identity!.spoolUuid)||!equal(after.identity!.spoolGenesisDigest,before.identity!.spoolGenesisDigest)||!equal(after.predecessorDelegationDigest,old.digest)||equal(after.jobPublicKey,before.jobPublicKey)||equal(after.delegationId,before.delegationId))reject("RenewalFork");const os=before.scope!,ns=after.scope!;if(!subset(ns,os))reject("RenewalFork");let consumed=0n;for(const slot of committed.slots){const b=os.branches.find(b=>b.refName===slot.refName&&b.slotId===slot.slotId);if(b){if(slot.resultBytes>b.maxResultBytes)reject("RenewalFork");consumed+=slot.resultBytes;}if(ns.branches.some(b=>b.refName===slot.refName&&b.slotId===slot.slotId))reject("RenewalFork");}const removed=os.branches.filter(b=>committed.slots.some(s=>s.refName===b.refName&&s.slotId===b.slotId)).length;if(ns.maxOperations>os.maxOperations-removed||ns.maxResultBytes>os.maxResultBytes-consumed||after.branchManifest.some(m=>!before.branchManifest.some(old=>equal(old.genesisAuthorityDigest,m.genesisAuthorityDigest)&&old.limit&&m.limit&&old.limit.refName===m.limit.refName&&equal(old.limit.genesisDigest,m.limit.genesisDigest))))reject("RenewalFork");await auth(after.delegatingPublicKey,RENEWAL_DOMAIN,api.ImportJobRenewalV1Schema,r,signed.delegatingSignature);return next;}
export function checkImportSlotReplay(m:api.ImportResultManifestV1,signed:api.SignedDelegatedImportOperationV1):boolean{validateImportManifest(m);const o=signed.body;if(!o)reject("Canonical");if(!equal(m.logicalJobId,o.logicalJobId)||!equal(m.retryLineageId,o.retryLineageId))reject("Scope");const s=m.slots.find(s=>s.refName===o.refName&&s.slotId===o.slotId);if(!s)return false;if(!equal(s.signedOperationDigest,signedOperationDigest(signed))||!equal(s.resultingFrontierDigest,o.resultingFrontierDigest)||s.resultBytes!==o.resultBytes)reject("SlotConflict");return true;}
export function requireHybridPeer(protocol:ProtocolCompatibility|undefined):void{if(!protocol||protocol.protocolVersion!==2||protocol.mandatoryFeatures.length!==1||protocol.mandatoryFeatures[0]!==1)reject("Protocol");}
export async function verifyImportPublication(operation:api.SignedDelegatedImportOperationV1,delegation:VerifiedImportDelegation,manifest:api.ImportResultManifestV1,statement:SignedHostedWitnessStatementV1,set:VerifiedWitnessSet,proof:HostedWitnessHistoryProofV1|undefined,now:bigint){await verifyDelegatedImportOperation(operation,delegation);if(!checkImportSlotReplay(manifest,operation))reject("Scope");const o=operation.body!,{body:d,digest}=read(delegation),s=statement.body,id=d.identity!;if(!s)reject("Canonical");const payload=create(api.ImportPublicationWitnessV1Schema,{formatVersion:1,signedOperationDigest:signedOperationDigest(operation),delegationDigest:digest,logicalJobId:o.logicalJobId,retryLineageId:o.retryLineageId,physicalOperationId:o.physicalOperationId,refName:o.refName,slotId:o.slotId,hashAlgorithm:o.hashAlgorithm,observedCommitOid:o.observedCommitOid,expectedFrontierDigest:o.expectedFrontierDigest,resultingFrontierDigest:o.resultingFrontierDigest,terminalManifestDigest:manifestDigest(manifest)});if(s.purpose!==3||!equal(s.spoolUuid,id.spoolUuid)||!equal(s.spoolGenesisDigest,id.spoolGenesisDigest)||!equal(s.ownerId,id.ownerId)||!equal(s.ownerStateHash,id.ownerStateHash)||s.ownershipTransferSequence!==id.ownershipTransferSequence||!equal(s.authorityDigest,digest)||!operation.jobSignature||!equal(s.originalSignaturesDigest,hash(operation.jobSignature.signature))||!equal(s.canonicalPayload,canonicalHybridV1(api.ImportPublicationWitnessV1Schema,payload))||s.basis!==1)reject("Scope");interval(d.notBeforeUnixSeconds,d.expiresAtUnixSeconds,s.observedAtUnixMillis/1000n);return resolveWitnessStatement(set,statement,proof,false,now);}

export function checkImportJobFence(logicalJobId:Uint8Array,activeDigest:Uint8Array,expectedEpoch:bigint,active:VerifiedImportDelegation,durableEpoch:bigint):void{const d=read(active);if(!equal(logicalJobId,d.body.logicalJobId))reject("Scope");if(expectedEpoch!==durableEpoch||!equal(activeDigest,d.digest))reject("StaleContext");}

export interface ImportSigner{publicKey:Uint8Array;sign(digest:Uint8Array):Promise<Uint8Array>;}
async function signature(domain:string,schema:Parameters<typeof canonicalHybridV1>[0],body:Parameters<typeof canonicalHybridV1>[1],signer:ImportSigner):Promise<AuthorizationSignature>{const digest=signingDigest(domain,schema,body);const signature=await signer.sign(digest);await verifySignature(signer.publicKey,digest,signature);return {$typeName:"heddle.api.v1alpha2.AuthorizationSignature",signerKeyId:keyId(signer.publicKey),signature};}
export async function signImportMemberPermission(body:api.ImportMemberPermissionV1,signer:ImportSigner){const b=clone(api.ImportMemberPermissionV1Schema,body);return create(api.SignedImportMemberPermissionV1Schema,{body:b,ownerSignature:await signature(PERMISSION_DOMAIN,api.ImportMemberPermissionV1Schema,b,signer)});}
export async function signImportGenesisAuthority(body:api.ImportGenesisAuthorityV1,signer:ImportSigner){const b=clone(api.ImportGenesisAuthorityV1Schema,body);if(!equal(b.creatorPublicKey,signer.publicKey))reject("Signature");return create(api.SignedImportGenesisAuthorityV1Schema,{body:b,creatorSignature:await signature(GENESIS_DOMAIN,api.ImportGenesisAuthorityV1Schema,b,signer)});}
export async function signImportDelegation(body:api.ImportJobDelegationV1,signer:ImportSigner){const b=clone(api.ImportJobDelegationV1Schema,body);if(!equal(b.delegatingPublicKey,signer.publicKey))reject("Signature");return create(api.SignedImportJobDelegationV1Schema,{body:b,delegatingSignature:await signature(DELEGATION_DOMAIN,api.ImportJobDelegationV1Schema,b,signer)});}
export async function signImportRenewal(body:api.ImportJobRenewalV1,signer:ImportSigner){const b=clone(api.ImportJobRenewalV1Schema,body);if(!b.replacement?.body||!equal(b.replacement.body.delegatingPublicKey,signer.publicKey))reject("Signature");return create(api.SignedImportJobRenewalV1Schema,{body:b,delegatingSignature:await signature(RENEWAL_DOMAIN,api.ImportJobRenewalV1Schema,b,signer)});}
export async function signDelegatedImportOperation(body:api.DelegatedImportOperationV1,signer:ImportSigner){const b=clone(api.DelegatedImportOperationV1Schema,body);return create(api.SignedDelegatedImportOperationV1Schema,{body:b,jobSignature:await signature(OPERATION_DOMAIN,api.DelegatedImportOperationV1Schema,b,signer)});}
