import { clone, toBinary } from "@bufbuild/protobuf";
import * as common from "../common/hosted_witness_pb.js";
import { canonicalHybridV1, signingDigest, hash, equal, compare, join, utf8, width, verifySignature, u32, integer, reject, canonicalHttps } from "./_hybrid-codec.js";
export { HybridContractError } from "./_hybrid-codec.js";
export const SET_DOMAIN="heddle-hosted-witness-set-v1\0",MAX_SET_BYTES=1048576,MAX_ENTRIES=4096,MAX_PROOF_BYTES=4096,MAX_SIBLINGS=64;
export function witnessId(key:Uint8Array):Uint8Array{return hash(utf8.encode("heddle-hosted-witness-key-v1\0"),key);}
export function setSigningBytes(body:common.HostedWitnessSetV1):Uint8Array{const bytes=join(utf8.encode(SET_DOMAIN),canonicalHybridV1(common.HostedWitnessSetV1Schema,body));if(bytes.length+96>MAX_SET_BYTES)reject("Bounds");return bytes;}
export function purposeDomain(purpose:number):string{switch(purpose){case 1:return "heddle-import-genesis-first-admission-witness-v1";case 2:return "heddle-import-authority-first-admission-witness-v1";case 3:return "heddle-import-publication-witness-v1";case 4:return "heddle-hosted-landing-witness-v1";default:return reject("Version");}}
export function statementSigningDigest(body:common.HostedWitnessStatementV1):Uint8Array{return signingDigest(purposeDomain(body.purpose),common.HostedWitnessStatementV1Schema,body);}
export function leafDigest(purpose:number,canonical:Uint8Array,signature:Uint8Array):Uint8Array{purposeDomain(purpose);width(signature,64);if(!canonical.length||canonical.length>131072)reject("Bounds");return hash(Uint8Array.of(0),u32(purpose),integer(BigInt(canonical.length)),canonical,signature);}
export interface WitnessSetExpectation{authority:string;rootId:string;rootPublicKey:Uint8Array;rootEpoch:bigint;nowUnixMillis:bigint;clockFloorUnixMillis:bigint;knownJobKeys:readonly Uint8Array[];}
export interface VerifiedWitnessSet{readonly body:common.HostedWitnessSetV1;readonly digest:Uint8Array;readonly rootEpoch:bigint;}
const sets=new WeakMap<object,{body:common.HostedWitnessSetV1;digest:Uint8Array;rootEpoch:bigint}>();
function read(s:VerifiedWitnessSet){return sets.get(s)??reject("Canonical");}
/** Restore ONLY previously accepted receiver-owned durable history. Its expired
 * snapshot cannot authorize new work; authenticate a fresh set at actual time
 * with this high-water and the separately persisted wall-clock floor. */
export async function restoreWitnessHistorySnapshot(signed:common.SignedHostedWitnessSetV1,selected:WitnessSetExpectation):Promise<VerifiedWitnessSet>{if(!signed.body)reject("Canonical");return verifyWitnessSet(signed,{...selected,nowUnixMillis:signed.body.issuedAtUnixMillis,clockFloorUnixMillis:0n});}
export async function verifyWitnessSet(signed:common.SignedHostedWitnessSetV1,e:WitnessSetExpectation,previous?:VerifiedWitnessSet):Promise<VerifiedWitnessSet>{
  e={...e,rootPublicKey:e.rootPublicKey.slice(),knownJobKeys:e.knownJobKeys.map(k=>k.slice())};
  const snapshot=clone(common.SignedHostedWitnessSetV1Schema,signed);if(toBinary(common.SignedHostedWitnessSetV1Schema,snapshot).length>MAX_SET_BYTES)reject("Bounds");const b=snapshot.body;if(!b)reject("Canonical");if(b.formatVersion!==1)reject("Version");if(b.deploymentAuthority!==e.authority||b.descriptorRootId!==e.rootId)reject("Root");const input=setSigningBytes(b);await verifySignature(e.rootPublicKey,input,snapshot.rootSignature);const digest=hash(input);if(!equal(digest,snapshot.bodyDigest))reject("Canonical");if(b.generation===0n||!b.entries.length||b.entries.length>MAX_ENTRIES)reject("Semantic");if(e.nowUnixMillis<e.clockFloorUnixMillis)reject("StaleContext");if(b.issuedAtUnixMillis<0n||b.validUntilUnixMillis<=b.issuedAtUnixMillis||b.validUntilUnixMillis-b.issuedAtUnixMillis>300000n)reject("Semantic");if(e.nowUnixMillis<b.issuedAtUnixMillis||e.nowUnixMillis>=b.validUntilUnixMillis)reject("Expired");canonicalHttps(b.deploymentAuthority,true);if(!b.descriptorRootId||utf8.encode(b.descriptorRootId).length>256)reject("Bounds");width(b.currentExecutorId,32);let current=0;
  b.entries.forEach((v,i)=>{width(v.publicKey,32);width(v.executorId,32);if(!equal(v.executorId,witnessId(v.publicKey))||(i>0&&compare(b.entries[i-1]!.executorId,v.executorId)>=0)||b.entries.slice(0,i).some(p=>equal(p.publicKey,v.publicKey))||equal(v.publicKey,e.rootPublicKey))reject("Semantic");if(v.role!==1||e.knownJobKeys.some(k=>equal(k,v.publicKey)))reject("JobAsWitness");if(!v.purposes.length||v.purposes.some(p=>p<1||p>4)||v.purposes.some((p,i)=>i>0&&v.purposes[i-1]!>=p)||v.activeFromUnixMillis<0n||v.activeUntilUnixMillis<=v.activeFromUnixMillis)reject("Semantic");switch(v.state){case 1:current++;if(!equal(v.executorId,b.currentExecutorId)||v.activeFromUnixMillis>b.issuedAtUnixMillis||v.activeUntilUnixMillis<b.validUntilUnixMillis||v.archiveRoot.length||v.archiveLeafCount!==0n||v.revokedAtUnixMillis!==0n)reject("Semantic");break;case 2:width(v.archiveRoot,32);if(v.activeUntilUnixMillis>b.issuedAtUnixMillis||v.revokedAtUnixMillis!==0n||(v.archiveLeafCount===0n&&!equal(v.archiveRoot,hash(new Uint8Array()))))reject("Semantic");break;case 3:if(v.revokedAtUnixMillis<=0n||v.revokedAtUnixMillis>b.issuedAtUnixMillis||(v.archiveRoot.length!==0&&v.archiveRoot.length!==32)||(v.archiveRoot.length===0&&v.archiveLeafCount!==0n))reject("Semantic");break;default:reject("Semantic");}});
  if(current!==1)reject("Semantic");if(previous){const old=read(previous);if(old.rootEpoch!==e.rootEpoch)reject("StaleContext");if(b.generation<old.body.generation||(b.generation===old.body.generation&&!equal(digest,old.digest)))reject("HighWater");for(const before of old.body.entries){const after=b.entries.find(v=>equal(v.executorId,before.executorId));if(!after||!equal(before.publicKey,after.publicKey)||before.role!==after.role||before.purposes.join()!==after.purposes.join()||before.activeFromUnixMillis!==after.activeFromUnixMillis||(before.state!==1&&(before.activeUntilUnixMillis!==after.activeUntilUnixMillis||!equal(before.archiveRoot,after.archiveRoot)||before.archiveLeafCount!==after.archiveLeafCount))||(before.state===2&&after.state===1)||(before.state===3&&(after.state!==3||after.revokedAtUnixMillis!==before.revokedAtUnixMillis))||(before.state===1&&after.state!==1&&after.activeUntilUnixMillis<old.body.validUntilUnixMillis))reject("Transition");}}
  const result={get body(){return clone(common.HostedWitnessSetV1Schema,b);},get digest(){return digest.slice();},rootEpoch:e.rootEpoch};sets.set(result,{body:b,digest,rootEpoch:e.rootEpoch});return result;
}
function split(n:bigint):bigint{let k=1n;while(k*2n<n)k*=2n;return k;}
export function merkleRoot(leaves:readonly Uint8Array[]):Uint8Array{if(leaves.some(v=>v.length!==32)||leaves.some((v,i)=>i>0&&compare(leaves[i-1]!,v)>=0))reject("Canonical");function tree(a:readonly Uint8Array[]):Uint8Array{if(!a.length)return hash(new Uint8Array());if(a.length===1)return a[0]!.slice();const k=Number(split(BigInt(a.length)));return hash(Uint8Array.of(1),tree(a.slice(0,k)),tree(a.slice(k)));}return tree(leaves);}
export function verifyWitnessInclusion(leaf:Uint8Array,p:common.HostedWitnessHistoryProofV1,entry:common.HostedWitnessEntryV1):void{if(toBinary(common.HostedWitnessHistoryProofV1Schema,p).length>MAX_PROOF_BYTES||p.siblings.length>MAX_SIBLINGS)reject("Bounds");if(leaf.length!==32||!equal(p.executorId,entry.executorId)||p.leafCount!==entry.archiveLeafCount||p.leafCount===0n||p.leafIndex>=p.leafCount||p.siblings.some(s=>s.length!==32))reject("Proof");const directions:boolean[]=[];function path(i:bigint,n:bigint){if(n===1n)return;const k=split(n);if(i<k){path(i,k);directions.push(false);}else{path(i-k,n-k);directions.push(true);}}path(p.leafIndex,p.leafCount);if(directions.length!==p.siblings.length)reject("Proof");let root=leaf;directions.forEach((right,i)=>{root=right?hash(Uint8Array.of(1),p.siblings[i]!,root):hash(Uint8Array.of(1),root,p.siblings[i]!);});if(!equal(root,entry.archiveRoot))reject("Proof");}
export interface ResolvedWitnessStatement{readonly statementDigest:Uint8Array;}
const contexts=new WeakMap<object,{statementDigest:Uint8Array;setDigest:Uint8Array;generation:bigint;rootEpoch:bigint}>();
export async function resolveWitnessStatement(set:VerifiedWitnessSet,signed:common.SignedHostedWitnessStatementV1,proof:common.HostedWitnessHistoryProofV1|undefined,newWork:boolean,now:bigint):Promise<ResolvedWitnessStatement>{const state=read(set),b=state.body;if(now<b.issuedAtUnixMillis||now>=b.validUntilUnixMillis)reject("Expired");const snapshot=clone(common.SignedHostedWitnessStatementV1Schema,signed),s=snapshot.body;if(!s)reject("Canonical");if(s.formatVersion!==1)reject("Version");for(const v of [s.executorId,s.spoolGenesisDigest,s.ownerId,s.ownerStateHash,s.policyStateHash,s.publisherKeyId,s.authorityDigest,s.originalSignaturesDigest])width(v,32);width(s.spoolUuid,16);width(s.hostTransactionId,16);if(!s.canonicalPayload.length||s.canonicalPayload.length>65536)reject("Bounds");if(![1,2].includes(s.basis)||s.admissionOrder===0n)reject("Semantic");const entry=b.entries.find(v=>equal(v.executorId,s.executorId));if(!entry)reject("Root");if(entry.state===3)reject("Revoked");if(!entry.purposes.includes(s.purpose))reject("Scope");if(s.observedAtUnixMillis<entry.activeFromUnixMillis||s.observedAtUnixMillis>=entry.activeUntilUnixMillis||(newWork&&(entry.state!==1||s.observedAtUnixMillis!==now)))reject("Expired");await verifySignature(entry.publicKey,statementSigningDigest(s),snapshot.signature);const digest=leafDigest(s.purpose,canonicalHybridV1(common.HostedWitnessStatementV1Schema,s),snapshot.signature);if(entry.state===2){if(!proof||proof.purpose!==s.purpose)reject("Proof");verifyWitnessInclusion(digest,proof,entry);}const result={get statementDigest(){return digest.slice();}};contexts.set(result,{statementDigest:digest,setDigest:state.digest,generation:b.generation,rootEpoch:state.rootEpoch});return result;}
export function recheckWitnessContext(context:ResolvedWitnessStatement,set:VerifiedWitnessSet,signed:common.SignedHostedWitnessStatementV1,now:bigint):void{const c=contexts.get(context)??reject("Canonical"),n=read(set),s=signed.body;if(!s)reject("Canonical");if(c.rootEpoch!==n.rootEpoch||c.generation!==n.body.generation||!equal(c.setDigest,n.digest)||!equal(c.statementDigest,leafDigest(s.purpose,canonicalHybridV1(common.HostedWitnessStatementV1Schema,s),signed.signature)))reject("StaleContext");if(now<n.body.issuedAtUnixMillis||now>=n.body.validUntilUnixMillis)reject("Expired");}
export function validateWitnessLookup(request:{executorId:Uint8Array;statementLeafDigest:Uint8Array}):void{width(request.executorId,32);width(request.statementLeafDigest,32);}
