import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { createPrivateKey, createPublicKey, sign } from 'node:crypto';
import { create } from '@bufbuild/protobuf';
import { SourceAnchorSchema, AnnotationTagSchema, SourceTargetReferenceSchema } from '../packages/typescript/dist/v2alpha1/collaboration_pb.js';
import { Audience } from '../packages/typescript/dist/v2alpha1/administration_pb.js';
import { SignedRecordSchema } from '../packages/typescript/dist/v2alpha1/common_pb.js';
import { signDiscussion, signContext, verifyCollaboration, sourceTargetReference, collaborationVisibility, textAnnotationTag } from '../packages/typescript/dist/v2alpha1/collaboration.js';
import { encode, decode } from '../packages/typescript/dist/v2alpha1/_collaboration-msgpack.js';

// Generated by Rust thread_api::collaboration::canonical_browser_interop_vectors.
// This file must be refreshed from that test, never from the TypeScript encoder.
const fixtures = Object.fromEntries(readFileSync(new URL('./fixtures/collaboration-v2-rust.txt', import.meta.url), 'utf8').trim().split('\n').map(line => {
  const [name, key, canonical, signature, id] = line.split(' ');
  return [name, { record: create(SignedRecordSchema, { format: 'heddle-thread-operation-v1',
    canonicalRecord: Buffer.from(canonical, 'hex'), signatures: [{ publicKey: Buffer.from(key, 'hex'), signature: Buffer.from(signature, 'hex') }] }), id }];
}));
const key = createPrivateKey({ key: Buffer.concat([Buffer.from('302e020100300506032b657004220420', 'hex'), Buffer.alloc(32, 7)]), format: 'der', type: 'pkcs8' });
const signer = { publicKey: new Uint8Array(createPublicKey(key).export({ format: 'der', type: 'spki' }).subarray(-32)),
  sign: async bytes => new Uint8Array(sign(null, bytes, key)) };
const scope = { spoolId: '00000000-0000-0000-0000-000000000001', threadId: new Uint8Array(32).fill(2) };
const actor = { principalId: '00000000-0000-0000-0000-000000000003', agentId: 'agent-4' };
const discussionId = 'disc-01980000-0000-7000-8000-000000000123';
const command = action => ({ discussionId, clientOperationId: 'operation-1', scope, actor,
  occurredAtMs: 100n, author: { name: 'Account' }, action });
const openCommand = command({ kind: 'open', blocking: true, title: 'Review', anchor: { kind: 'repository' }, visibility: 'public', body: 'First turn' });
const contextCommand = { scope, actor, occurredAtMs: 100n, contextId: '00000000-0000-0000-0000-000000000009', anchor: { kind: 'repository' }, content: 'Design rationale', tags: [textAnnotationTag('decision')] };

test('management references retain exact canonical kind in signed context', async () => {
  for (const recordKind of ['mount', 'support_access', 'device_record', 'delegation', 'recovery', 'owner_transition', 'billing', 'evidence', 'check_acknowledgement', 'provider_connection', 'remote_link']) {
    const record = await signContext({ ...contextCommand,
      mentions: [{ kind: 'record', recordKind, spoolId: scope.spoolId, id: 'record-1' }],
    }, [], signer);
    await verifyCollaboration(record);
    const outer = decode(record.canonicalRecord);
    const inner = decode(Uint8Array.from(outer.body.canonical));
    assert.equal(inner.metadata.mentions[0].record_kind, recordKind);
    assert.equal(inner.metadata.mentions[0].id, 'record-1');
  }
});
function exact(actual, fixture) {
  assert.deepEqual(actual.canonicalRecord, new Uint8Array(fixture.record.canonicalRecord));
  assert.deepEqual(actual.signatures[0].signature, new Uint8Array(fixture.record.signatures[0].signature));
}

test('browser Open, Append, Resolve, Reopen and Context match independent Rust bytes and signatures', async () => {
  const open = await signDiscussion(openCommand, [], signer); exact(open, fixtures.open);
  const append = await signDiscussion({ ...command({ kind: 'append', body: 'See the reviewed state' }), mentions: [{ kind: 'state', spoolId: scope.spoolId, id: new Uint8Array(32).fill(5) }] }, [open], signer); exact(append, fixtures.append);
  const resolve = await signDiscussion(command({ kind: 'resolve', resolution: { kind: 'dismissed', reason: 'Verified' } }), [append], signer); exact(resolve, fixtures.resolve);
  const reopen = await signDiscussion(command({ kind: 'reopen', reason: 'New evidence' }), [resolve], signer); exact(reopen, fixtures.reopen);
  exact(await signContext(contextCommand, [], signer), fixtures.context);
  for (const fixture of Object.values(fixtures)) {
    const verified = await verifyCollaboration(fixture.record);
    assert.equal(Buffer.from(verified.operationId).toString('hex'), fixture.id);
  }
});

test('parent signatures, record scope and duplicate parents are validated before signing', async () => {
  let signed = 0;
  const counting = { ...signer, sign: bytes => { signed++; return signer.sign(bytes); } };
  const altered = structuredClone(fixtures.open.record);
  altered.signatures[0].signature[0] ^= 1;
  await assert.rejects(signDiscussion(command({ kind: 'append', body: 'Reply' }), [altered], counting), /Invalid collaboration author signature/);
  await assert.rejects(signDiscussion({ ...command({ kind: 'append', body: 'Reply' }), scope: { ...scope, spoolId: '00000000-0000-0000-0000-000000000005' } }, [fixtures.open.record], counting), /another record or scope/);
  await assert.rejects(signDiscussion(command({ kind: 'append', body: 'Reply' }), [fixtures.open.record, fixtures.open.record], counting), /Duplicate/);
  await assert.rejects(signContext(contextCommand, [fixtures.open.record], counting), /another record or scope/);
  assert.equal(signed, 0);
});

test('concurrent discussion heads join deterministically regardless of observation ordering', async () => {
  const left = await signDiscussion(command({ kind: 'append', body: 'Left' }), [fixtures.open.record], signer);
  const right = await signDiscussion(command({ kind: 'append', body: 'Right' }), [fixtures.open.record], signer);
  const merge = command({ kind: 'append', body: 'Combined' });
  const joined = await signDiscussion(merge, [left, right], signer);
  assert.deepEqual(joined, await signDiscussion(merge, [right, left], signer));
  assert.equal(decode(joined.canonicalRecord).parents.length, 2);
});

test('context revisions bind outer causal IDs directly and reject changing their record identity', async () => {
  const revision = await signContext({ ...contextCommand, content: 'Updated rationale' }, [fixtures.context.record], signer);
  const outer = decode(revision.canonicalRecord);
  const inner = decode(Uint8Array.from(outer.body.canonical));
  assert.equal(Buffer.from(inner.parents[0]).toString('hex'), fixtures.context.id);
  assert.deepEqual(inner.parents, outer.parents);
  await assert.rejects(signContext({ ...contextCommand, contextId: '00000000-0000-0000-0000-000000000010' }, [fixtures.context.record], signer), /another record or scope/);
});

test('source spans and actor identities are bounded before signing', async () => {
  await assert.rejects(signDiscussion({ ...openCommand, actor: { ...actor, principalId: '00000000-0000-0000-0000-000000000000' } }, [], signer), /non-nil UUID/);
  await assert.rejects(signDiscussion({ ...openCommand, actor: { ...actor, agentId: 'agent\nother' } }, [], signer), /text/);
  await assert.rejects(signDiscussion({ ...openCommand, action: { ...openCommand.action, anchor: { kind: 'source', revision: { kind: 'git_commit', oid: 'a'.repeat(40) }, path: 'src/main.rs', startLine: 12, endLine: 11 } } }, [], signer), /Invalid source span/);
  await assert.rejects(signDiscussion(command({ kind: 'append', body: 'x'.repeat(256 * 1024 + 1) }), [], signer), /unbounded/);
});

test('MessagePack rejects nonminimal integers, duplicate keys, trailing data and oversized arrays', () => {
  for (const bytes of [[0xcc, 1], [0x82, 0xa1, 0x61, 1, 0xa1, 0x61, 2], [1, 2], [0xdd, 0xff, 0xff, 0xff, 0xff]]) assert.throws(() => decode(Uint8Array.from(bytes)));
  for (const value of [null, true, false, -33n, -129n, -32769n, -2147483649n, 4294967296n, -9223372036854775808n, 'é'.repeat(180), new Uint8Array(256), []]) assert.deepEqual(encode(decode(encode(value))), encode(value));
});

test('signed malformed turn bodies and root/non-root frontiers cannot become parents', async () => {
  async function signMutated(mutate) {
    const record = structuredClone(fixtures.open.record);
    const outer = decode(record.canonicalRecord);
    const inner = decode(Uint8Array.from(outer.body.canonical));
    mutate(inner);
    outer.body.canonical = Array.from(encode(inner));
    record.canonicalRecord = encode(outer);
    record.signatures[0].signature = await signer.sign(Buffer.concat([Buffer.from('heddle-thread-operation-v1\0'), record.canonicalRecord]));
    return record;
  }
  await assert.rejects(verifyCollaboration(await signMutated(inner => { inner.body.turn.body = 'Changed without matching content hash'; })), /content hash/);
  await assert.rejects(verifyCollaboration(await signMutated(inner => { inner.body = { kind: 'append_turn', turn: inner.body.turn }; })), /empty causal frontier/);
  await assert.rejects(signDiscussion(openCommand, [fixtures.open.record], signer), /empty causal frontier/);
  await assert.rejects(signDiscussion(command({ kind: 'append', body: 'Reply' }), [], signer), /empty causal frontier/);
});

test('independent publishers of the same inner record produce one inner parent and two outer parents', async () => {
  const otherKey = createPrivateKey({ key: Buffer.concat([Buffer.from('302e020100300506032b657004220420', 'hex'), Buffer.alloc(32, 8)]), format: 'der', type: 'pkcs8' });
  const otherSigner = { publicKey: new Uint8Array(createPublicKey(otherKey).export({ format: 'der', type: 'spki' }).subarray(-32)), sign: async bytes => new Uint8Array(sign(null, bytes, otherKey)) };
  const other = await signDiscussion(openCommand, [], otherSigner);
  const joined = await signDiscussion(command({ kind: 'append', body: 'Joined' }), [fixtures.open.record, other], signer);
  const outer = decode(joined.canonicalRecord);
  assert.equal(outer.parents.length, 2);
  assert.equal(decode(Uint8Array.from(outer.body.canonical)).parents.length, 1);
});

test('exact state and Git source spans match independent Rust fixtures', async () => {
  for (const [name, revision] of [['source_state', { kind: 'state', stateId: new Uint8Array(32).fill(5) }], ['source_git', { kind: 'git_commit', oid: 'a'.repeat(40) }]]) {
    const source = command({ kind: 'open', blocking: true, title: 'Review source', visibility: 'public', body: 'Check these lines', anchor: { kind: 'source', revision, path: 'src/main.rs', symbolId: 'run', startLine: 12, endLine: 18 } });
    exact(await signDiscussion(source, [], signer), fixtures[name]);
  }
});

test('explicit source target bindings survive primary anchors and tags and are signed', async () => {
  const bindings = [
    { case: 'viewedThread', value: true },
    { case: 'namedThread', value: { spool: { id: scope.spoolId }, id: { value: new Uint8Array(32).fill(8) } } },
    { case: 'pinnedRevision', value: { revision: { spool: { id: scope.spoolId }, revision: { case: 'state', value: { value: new Uint8Array(32).fill(5) } } } } },
  ];
  for (const binding of bindings) {
    const target = create(SourceTargetReferenceSchema, { targetId: new Uint8Array(32).fill(6), binding });
    const anchor = { kind: 'source', revision: { kind: 'state', stateId: new Uint8Array(32).fill(5) }, path: 'src/main.rs', symbolId: 'run', startLine: 12, endLine: 18, target };
    const record = await signDiscussion(command({ kind: 'open', blocking: true, title: 'Review source', visibility: 'public', body: 'Check these lines', anchor }), [], signer);
    const fixtureName = { viewedThread: 'viewed', namedThread: 'named', pinnedRevision: 'pinned' }[binding.case];
    exact(record, fixtures['target_' + fixtureName]);
    const outer = decode(record.canonicalRecord), inner = decode(Uint8Array.from(outer.body.canonical));
    assert.deepEqual(inner.body.anchor.source.target.target, Array(32).fill(6));
    assert.equal(inner.body.anchor.source.path, 'src/main.rs');
    await verifyCollaboration(record);
    const tag = create(AnnotationTagSchema, { tag: { case: 'source', value: { source: {
      revision: { spool: { id: scope.spoolId }, revision: { case: 'state', value: { value: new Uint8Array(32).fill(5) } } },
      thread: { spool: { id: scope.spoolId }, id: { value: scope.threadId } }, path: 'src/main.rs', target,
    } } } });
    const context = await signContext({ ...contextCommand, tags: [tag] }, [], signer);
    exact(context, fixtures['tag_' + fixtureName]);
    const contextInner = decode(Uint8Array.from(decode(context.canonicalRecord).body.canonical));
    assert.deepEqual(contextInner.tags[0].target.source.target, inner.body.anchor.source.target);
    inner.body.anchor.source.target.target[0] ^= 1;
    outer.body.canonical = Array.from(encode(inner));
    const changed = structuredClone(record); changed.canonicalRecord = encode(outer);
    await assert.rejects(verifyCollaboration(changed), /signature/);
  }
});

test('invalid source target binding is rejected before invoking signer', async () => {
  let signed = 0;
  const counting = { ...signer, sign: bytes => { signed++; return signer.sign(bytes); } };
  for (const binding of [undefined, { case: 'viewedThread', value: false },
    { case: 'namedThread', value: { spool: { id: scope.spoolId } } },
    { case: 'pinnedRevision', value: { revision: { spool: { id: scope.spoolId } } } },
    { case: 'pinnedRevision', value: { revision: { spool: { id: scope.spoolId }, revision: { case: 'gitCommitOid', value: 'a'.repeat(40) } },
      thread: { spool: { id: '00000000-0000-0000-0000-000000000099' }, id: { value: scope.threadId } } } },
  ]) {
    const target = create(SourceTargetReferenceSchema, { targetId: new Uint8Array(32).fill(6), ...(binding ? { binding } : {}) });
    await assert.rejects(signContext({ ...contextCommand, anchor: { kind: 'source', revision: { kind: 'state', stateId: new Uint8Array(32).fill(5) }, path: 'src/main.rs', target } }, [], counting));
  }
  assert.equal(signed, 0);
});

test('native audiences preserve restrictions and reject lossy canonical tiers', async () => {
  assert.equal(collaborationVisibility(Audience.PUBLIC), 'public');
  assert.equal(collaborationVisibility(Audience.MEMBERS), 'internal');
  assert.deepEqual(collaborationVisibility(Audience.PRIVATE, 'my-devices'), { kind: 'private', label: 'my-devices' });
  for (const [audience, label] of [[Audience.UNSPECIFIED, ''], [Audience.PRIVATE, ''], [Audience.PRIVATE, ' '], [Audience.PUBLIC, 'secret'], [Audience.MEMBERS, 'secret']]) {
    assert.throws(() => collaborationVisibility(audience, label));
  }
  for (const visibility of ['typo', { kind: 'team_scoped', label: 'team' }, { kind: 'restricted', label: 'scope' }]) {
    await assert.rejects(() => signDiscussion(command({ ...openCommand.action, visibility }), [], signer), /no native discussion audience/);
  }
});

test('structured annotation tags match independent Rust signatures without numeric precision loss', async () => {
  const tag = value => create(AnnotationTagSchema, { tag: value });
  const tags = [textAnnotationTag('decision'),
    tag({ case: 'symbol', value: { name: 'authorize', target: { source: { revision: { spool: { id: scope.spoolId }, revision: { case: 'gitCommitOid', value: 'a'.repeat(40) } }, thread: { spool: { id: scope.spoolId }, id: { value: scope.threadId } }, path: 'src/auth.rs', symbolId: 'auth::authorize', startLine: 12, endLine: 18 } } } }),
    tag({ case: 'property', value: { key: 'confidence', value: { value: { case: 'decimal', value: { coefficient: 9n, scale: 1 } } } } }),
    tag({ case: 'property', value: { key: 'requires_review', value: { value: { case: 'boolean', value: false } } } }),
    tag({ case: 'property', value: { key: 'large', value: { value: { case: 'integer', value: 9223372036854775807n } } } }),
    tag({ case: 'property', value: { key: 'severity', value: { value: { case: 'text', value: 'high' } } } }),
  ];
  const record = await signContext({ ...contextCommand, extractedFrom: undefined, tags }, [], signer);
  exact(record, fixtures.structured_context);
  await verifyCollaboration(record);
  const invalid = structuredClone(tags); invalid[2].tag.value.value.value.value = { coefficient: 90n, scale: 2 };
  await assert.rejects(signContext({ ...contextCommand, tags: invalid }, [], signer), /normalized/);
  await assert.rejects(signContext({ ...contextCommand, tags: [...tags, structuredClone(tags[2])] }, [], signer), /duplicate/);
});

// Both SDKs consume these exact target IDs; Rust derives its copies from model cores.
test('shared source target interning preserves identity across materialized locations', () => {
  const source = create(SourceAnchorSchema, {
    revision: { spool: { id: '00000000-0000-0000-0000-000000000001' }, revision: { case: 'state', value: { value: new Uint8Array(32).fill(5) } } },
    thread: { spool: { id: '00000000-0000-0000-0000-000000000001' }, id: { value: new Uint8Array(32).fill(2) } }, path: 'src/main.rs',
  });
  const binding = { case: 'viewedThread', value: true };
  const vectors = JSON.parse(readFileSync(new URL('./fixtures/source-target-ids.json', import.meta.url), 'utf8'));
  for (const [kind, fields] of [['file', {}], ['lines', { startLine: 12, endLine: 18 }], ['symbol', { symbolId: 'main::run' }]]) {
    const original = create(SourceAnchorSchema, { ...source, ...fields });
    const target = sourceTargetReference(original, binding);
    assert.equal(Buffer.from(target.targetId).toString('hex'), vectors[kind]);
    const moved = create(SourceAnchorSchema, { ...original, path: 'renamed.rs', startLine: 20, endLine: 25, target });
    const pinned = { case: 'pinnedRevision', value: { revision: original.revision, thread: original.thread } };
    assert.deepEqual(sourceTargetReference(moved, pinned).targetId, target.targetId);
    assert.equal(moved.target.binding.case, 'viewedThread', 'helper does not mutate existing binding');
  }
  assert.throws(() => sourceTargetReference(create(SourceAnchorSchema, { ...source, startLine: 0, endLine: 2 }), binding));
  assert.throws(() => sourceTargetReference(source, { case: 'viewedThread', value: false }));
});
